export const QUERY_KEYS = {
  MEAL_CATEGORIES: 'MEAL_CATEGORIES',
  MEAL_HISTORIES: 'MEAL_HISTORIES',
  MY_DIARIES: 'MY_DIARIES',
  COLUMN_POSTS: 'COLUMN_POSTS',
  MY_EXERCISES: 'MY_EXERCISES',
} as const;
