export const ROUTE_PATHS = {
  MY_RECORDS: '/my-records',
  CHALLENGES: '/challenges',
  NOTIFICATIONS: '/notifications',
  CHARTS: '/charts',
  TARGETS: '/targets',
  COURSES: '/courses',
  COLUMNS: '/columns',
  SETTINGS: '/settings',
  REGISTER: '/register',
  OPERATING_COMPANY: '/operating-company',
  TERMS: '/terms',
  INFORMATION: '/information',
  LAW: '/law',
  INVESTIGATION: '/investigation',
} as const;
